//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonusApp.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BonusApp.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Coupon.
        /// </summary>
        public static string AddCoupon {
            get {
                return ResourceManager.GetString("AddCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Coupon to Client.
        /// </summary>
        public static string AddCouponClient {
            get {
                return ResourceManager.GetString("AddCouponClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the client.
        /// </summary>
        public static string AreYouSureToDelete {
            get {
                return ResourceManager.GetString("AreYouSureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the coupon.
        /// </summary>
        public static string AreYouSureToDeleteCoupon {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to set.
        /// </summary>
        public static string AreYouSureWantToSetFirstPart {
            get {
                return ResourceManager.GetString("AreYouSureWantToSetFirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discount pages?.
        /// </summary>
        public static string AreYouSureWantToSetSecondPart {
            get {
                return ResourceManager.GetString("AreYouSureWantToSetSecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to see coupon details.
        /// </summary>
        public static string ClickToSeeCouponDetails {
            get {
                return ResourceManager.GetString("ClickToSeeCouponDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to set pages.
        /// </summary>
        public static string ClickToSetPages {
            get {
                return ResourceManager.GetString("ClickToSetPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Details.
        /// </summary>
        public static string ClientDetails {
            get {
                return ResourceManager.GetString("ClientDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client List.
        /// </summary>
        public static string ClientList {
            get {
                return ResourceManager.GetString("ClientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon.
        /// </summary>
        public static string Coupon {
            get {
                return ResourceManager.GetString("Coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coupon has been created.
        /// </summary>
        public static string CouponHasBeenCreated {
            get {
                return ResourceManager.GetString("CouponHasBeenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Id.
        /// </summary>
        public static string CouponId {
            get {
                return ResourceManager.GetString("CouponId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon List.
        /// </summary>
        public static string CouponList {
            get {
                return ResourceManager.GetString("CouponList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Name.
        /// </summary>
        public static string CouponName {
            get {
                return ResourceManager.GetString("CouponName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupons have been added.
        /// </summary>
        public static string CouponsHaveBeenAdded {
            get {
                return ResourceManager.GetString("CouponsHaveBeenAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupons selected.
        /// </summary>
        public static string CouponsSelected {
            get {
                return ResourceManager.GetString("CouponsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Type.
        /// </summary>
        public static string CouponType {
            get {
                return ResourceManager.GetString("CouponType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Types.
        /// </summary>
        public static string CouponTypes {
            get {
                return ResourceManager.GetString("CouponTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Client.
        /// </summary>
        public static string CreateClient {
            get {
                return ResourceManager.GetString("CreateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Coupon.
        /// </summary>
        public static string CreateCoupon {
            get {
                return ResourceManager.GetString("CreateCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Client.
        /// </summary>
        public static string CreateNewClient {
            get {
                return ResourceManager.GetString("CreateNewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Delete.
        /// </summary>
        public static string DisableDelete {
            get {
                return ResourceManager.GetString("DisableDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not have any coupon.
        /// </summary>
        public static string DoesNotHaveAnyCoupon {
            get {
                return ResourceManager.GetString("DoesNotHaveAnyCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Client.
        /// </summary>
        public static string EditClient {
            get {
                return ResourceManager.GetString("EditClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Coupon.
        /// </summary>
        public static string EditCoupon {
            get {
                return ResourceManager.GetString("EditCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails.
        /// </summary>
        public static string Emails {
            get {
                return ResourceManager.GetString("Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Delete.
        /// </summary>
        public static string EnableDelete {
            get {
                return ResourceManager.GetString("EnableDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: The coupons could not have been added.
        /// </summary>
        public static string ErrorAddingCoupon {
            get {
                return ResourceManager.GetString("ErrorAddingCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: The discount could not be applied....
        /// </summary>
        public static string ErrorAplyingDiscount {
            get {
                return ResourceManager.GetString("ErrorAplyingDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. User have not been created.
        /// </summary>
        public static string ErrorCreatingUser {
            get {
                return ResourceManager.GetString("ErrorCreatingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have been sent.
        /// </summary>
        public static string HaveBeenSent {
            get {
                return ResourceManager.GetString("HaveBeenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued Coupon List.
        /// </summary>
        public static string IssuedCouponList {
            get {
                return ResourceManager.GetString("IssuedCouponList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued date.
        /// </summary>
        public static string IssuedDate {
            get {
                return ResourceManager.GetString("IssuedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New client.
        /// </summary>
        public static string NewClient {
            get {
                return ResourceManager.GetString("NewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No client found....
        /// </summary>
        public static string NoClient {
            get {
                return ResourceManager.GetString("NoClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Coupon Found.
        /// </summary>
        public static string NoCouponFound {
            get {
                return ResourceManager.GetString("NoCouponFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Coupon Issued.
        /// </summary>
        public static string NoCouponIssued {
            get {
                return ResourceManager.GetString("NoCouponIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon has been added.
        /// </summary>
        public static string OkAddingCoupon {
            get {
                return ResourceManager.GetString("OkAddingCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The discount has been applied.
        /// </summary>
        public static string OkAplyingDiscount {
            get {
                return ResourceManager.GetString("OkAplyingDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario ha sido creado.
        /// </summary>
        public static string OkCreatingUser {
            get {
                return ResourceManager.GetString("OkCreatingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Incorrect.
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Sign In.
        /// </summary>
        public static string PleaseSignIn {
            get {
                return ResourceManager.GetString("PleaseSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed pages.
        /// </summary>
        public static string PrintedPages {
            get {
                return ResourceManager.GetString("PrintedPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining pages.
        /// </summary>
        public static string RemainingPages {
            get {
                return ResourceManager.GetString("RemainingPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Coupon.
        /// </summary>
        public static string SelectCoupon {
            get {
                return ResourceManager.GetString("SelectCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending email....
        /// </summary>
        public static string SendingEmail {
            get {
                return ResourceManager.GetString("SendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Pages.
        /// </summary>
        public static string SetPages {
            get {
                return ResourceManager.GetString("SetPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Pages to Discount.
        /// </summary>
        public static string SetPagesToDiscount {
            get {
                return ResourceManager.GetString("SetPagesToDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total clients.
        /// </summary>
        public static string TotalClients {
            get {
                return ResourceManager.GetString("TotalClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Coupon Pages.
        /// </summary>
        public static string TotalCouponPages {
            get {
                return ResourceManager.GetString("TotalCouponPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total coupons.
        /// </summary>
        public static string TotalCoupons {
            get {
                return ResourceManager.GetString("TotalCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Transactions.
        /// </summary>
        public static string TotalTransactions {
            get {
                return ResourceManager.GetString("TotalTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        public static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type number of pages.
        /// </summary>
        public static string TypeNumberOfPages {
            get {
                return ResourceManager.GetString("TypeNumberOfPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
